# Site settings
title: A blog about Bill Chen
description: A blog about Bill Chen's project and notes.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bill Chen
user_description: A graduate student just step into AI area, used to work on the graphic processing. eager to learn and never stop the pace.
user_title: Software Developer and AI beginer
email: zehuan@gmail.com
github_username:  BiliBiLL


exclude: ['package.json', 'src' , 'node_modules']
